from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk import download
import pandas as pd

# Download NLTK's VADER Lexicon
download("vader_lexicon")

# Initialize Sentiment Analyzer
sia = SentimentIntensityAnalyzer()

def analyze_sentiment(tweet):
    """
    Analyze the sentiment of a given tweet, ignoring neutral sentiment.

    Args:
        tweet (str): The text of the tweet.

    Returns:
        str: Sentiment label ('Positive' or 'Negative').
    """
    score = sia.polarity_scores(tweet)  # Get sentiment scores
    return 'Positive' if score['compound'] >= 0 else 'Negative'

def analyze_tweets_from_csv(csv_file):
    """
    Analyze sentiments for tweets read from a CSV file.

    Args:
        csv_file (str): Path to the CSV file containing tweets.

    Returns:
        DataFrame: A DataFrame containing tweets and their sentiments.
    """
    # Load the tweets from the CSV file
    df = pd.read_csv(csv_file)
    tweets = df['Tweet']  # Extract the Tweet column

    # Analyze sentiments
    sentiments = [analyze_sentiment(tweet) for tweet in tweets]
    df['Sentiment'] = sentiments  # Add the sentiment column

    return df

# Example Usage
if __name__ == "__main__":
    input_csv = "target_tweets.csv"  # Input CSV file generated by Grover's Algorithm

    # Analyze sentiments from the CSV file
    result_df = analyze_tweets_from_csv(input_csv)

    # Print results
    print(result_df)

