from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk import download
import pandas as pd
import time


# Downloading  NLTK's VADER Lexicon
download("vader_lexicon")

# Initialize Sentiment Analyzer
sia = SentimentIntensityAnalyzer()


def analyze_sentiment(tweet):
    """
    Analyze the sentiment of a given tweet, ignoring neutral sentiment.

    Args:
        tweet (str): The text of the tweet.

    Returns:
        str: Sentiment label ('Positive' or 'Negative').
    """
    score = sia.polarity_scores(tweet)  # Get sentiment scores
    return 'Positive' if score['compound'] >= 0 else 'Negative'

def analyze_tweets_from_csv(csv_file, output_csv):
    """
    Analyze sentiments for tweets read from a CSV file and save results to a new file.

    Args:
        csv_file (str): Path to the input CSV file containing tweets.
        output_csv (str): Path to save the output CSV with sentiments.

    Returns:
        DataFrame: A DataFrame containing tweets and their sentiments.
    """
    # Load the tweets from the CSV file
    df = pd.read_csv(csv_file)

    # Ensure required columns exist
    if "Tweet" not in df.columns:
        raise ValueError("The input CSV file must contain a 'Tweet' column!")

    # Analyze sentiments
    df["Sentiment"] = df["Tweet"].apply(analyze_sentiment)

    # Save the results to a new CSV file
    df.to_csv(output_csv, index=False)
    print(f"Analyzed tweets saved to {output_csv}")

    return df

if __name__ == "__main__":
    start_time = time.time()
    input_csv = "target_tweets.csv"  # Inputting the CSV file generated by Grover's Algorithm
    output_csv = "analyzed_tweets.csv"  # Output CSV file to save the results

    start_time = time.time()

    # Analyzing sentiments from the CSV file and save results
    result_df = analyze_tweets_from_csv(input_csv, output_csv)

    end_time = time.time()
    #Printing time required t
    print(f"Grover Pipeline Time: {end_time - start_time:.2f} seconds")


