from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk import download
import pandas as pd
import time

#downloading  NLTK's VADER Lexicon
download("vader_lexicon")

#intializing Sentiment Analyzer
sia = SentimentIntensityAnalyzer()

def analyze_sentiment(tweet):
    score = sia.polarity_scores(tweet)  #getting sentiment scores                   #tweet-Tscraped text data from twiiter.
    return 'Positive' if score['compound'] >= 0 else 'Negative'                 #sentiment label('Positive' or 'Negative')

def analyze_tweets_from_csv(csv_file, output_csv):
    # Load the tweets from the CSV file
    df = pd.read_csv(csv_file)

    #checking if it exist or not
    if "Tweet" not in df.columns:
        raise ValueError("The input CSV file must contain a 'Tweet' column!")

    #analyzing sentiments
    df["Sentiment"] = df["Tweet"].apply(analyze_sentiment)

    # Save the results to a new CSV file
    df.to_csv(output_csv, index=False)
    print(f"Analyzed tweets saved to {output_csv}")        #dataframe containing tweets and their sentiments

    return df

#calling main funciton
if __name__ == "__main__":
    start_time = time.time()
    input_csv = "target_tweets.csv"  #using csv file generated by Grover's algo
    output_csv = "analyzed_tweets.csv"  #o/p file to save results

    start_time = time.time()

    # Analyzing sentiments from the CSV file and save results
    result_df = analyze_tweets_from_csv(input_csv, output_csv)
    end_time = time.time()

    #Printing time required t
    print(f"Grover Pipeline Time: {end_time - start_time:.2f} seconds")


